services:
  mysql:
    image: mysql:latest
    container_name: humanresources_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: humanresourcesdb
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - humanresnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hrphpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "6060:80"
    depends_on:
      - mysql
    networks:
      - humanresnet

volumes:
  mysql_data:

networks:
  humanresnet:
